Title = "Episode Title"
CategoryName = "self.episode.Category"
CategoryID = "self.episode.CategoryID"
PlaylistName = "self.episode.Playlist"
PlaylistID = "self.episode.PlaylistID"
Full = "DEFAULTS.deliver_full[0]"
Podcast = "DEFAULTS.deliver_podcast[0]"
Short1 = "DEFAULTS.deliver_shorts[0]fdgsgdgd"
Short2 = "DEFAULTS.deliver_shorts[1]"
Short3 = "DEFAULTS.deliver_shorts[2]"
Thumbnail = "DEFAULTS.deliver_thumbnail[0]"
Markers = "DEFAULTS.edit_markers"
ScheduleTo = "2023-03-20T00:00:00"
Short1_ScheduleTo = "2023-03-15T00:00:00"
Short2_ScheduleTo = "2023-03-17T00:00:00"
Short3_ScheduleTo = "2023-03-19T00:00:00"
